name: NationKit
main: io.nationkit.operator
author: Timithius
version: 0.1.4-PREAPLHA
api-version: 1.17
depend: [dynmap, WorldGuard, WorldEdit]
commands:
  nation:
    description: Test!
  debug:
    description: test